DROP TABLE IF EXISTS Medicamento;

CREATE TABLE Medicamento(
    id      INT PRIMARY KEY,
    NOME    VARCHAR(255) NOT NULL,
    TIPO_LABORATORIO    VARCHAR(255),
    QUANTIDADE  INT NOT NULL,
    PRECO   DECIMAL NOT NULL
);